spring:
  liquibase:
    enabled: true

  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
worker:
  url: https://api.themoviedb.org/3/discover/movie
  token:
  requestInterval: "PT03H"